import React from 'react';
export const analyticsDetails = () => <div>analytics distinct</div>;
export const analytics_detail_0 = (p:any)=> <div>analytics 0 lane cost</div>;
export const analytics_detail_1 = (p:any)=> <div>analytics 1 KPI</div>;
export const analytics_detail_2 = (p:any)=> <div>analytics 2 OTD</div>;
export const analytics_detail_3 = (p:any)=> <div>analytics 3 utilization</div>;
export const analytics_detail_4 = (p:any)=> <div>analytics 4 lane cost</div>;
export const analytics_detail_5 = (p:any)=> <div>analytics 5 KPI</div>;
export const analytics_detail_6 = (p:any)=> <div>analytics 6 OTD</div>;
export const analytics_detail_7 = (p:any)=> <div>analytics 7 utilization</div>;
export const analytics_detail_8 = (p:any)=> <div>analytics 8 lane cost</div>;
export const analytics_detail_9 = (p:any)=> <div>analytics 9 KPI</div>;
export const analytics_detail_10 = (p:any)=> <div>analytics 10 OTD</div>;
export const analytics_detail_11 = (p:any)=> <div>analytics 11 utilization</div>;
export const analytics_detail_12 = (p:any)=> <div>analytics 12 lane cost</div>;
export const analytics_detail_13 = (p:any)=> <div>analytics 13 KPI</div>;
export const analytics_detail_14 = (p:any)=> <div>analytics 14 OTD</div>;
export const analytics_detail_15 = (p:any)=> <div>analytics 15 utilization</div>;
export const analytics_detail_16 = (p:any)=> <div>analytics 16 lane cost</div>;
export const analytics_detail_17 = (p:any)=> <div>analytics 17 KPI</div>;
export const analytics_detail_18 = (p:any)=> <div>analytics 18 OTD</div>;
export const analytics_detail_19 = (p:any)=> <div>analytics 19 utilization</div>;