import React from 'react';
export const routingDetails = () => <div>routing distinct</div>;
export const routing_detail_0 = (p:any)=> <div>routing 0 VRP</div>;
export const routing_detail_1 = (p:any)=> <div>routing 1 TSP</div>;
export const routing_detail_2 = (p:any)=> <div>routing 2 Dijkstra</div>;
export const routing_detail_3 = (p:any)=> <div>routing 3 time windows</div>;
export const routing_detail_4 = (p:any)=> <div>routing 4 VRP</div>;
export const routing_detail_5 = (p:any)=> <div>routing 5 TSP</div>;
export const routing_detail_6 = (p:any)=> <div>routing 6 Dijkstra</div>;
export const routing_detail_7 = (p:any)=> <div>routing 7 time windows</div>;
export const routing_detail_8 = (p:any)=> <div>routing 8 VRP</div>;
export const routing_detail_9 = (p:any)=> <div>routing 9 TSP</div>;
export const routing_detail_10 = (p:any)=> <div>routing 10 Dijkstra</div>;
export const routing_detail_11 = (p:any)=> <div>routing 11 time windows</div>;
export const routing_detail_12 = (p:any)=> <div>routing 12 VRP</div>;
export const routing_detail_13 = (p:any)=> <div>routing 13 TSP</div>;
export const routing_detail_14 = (p:any)=> <div>routing 14 Dijkstra</div>;
export const routing_detail_15 = (p:any)=> <div>routing 15 time windows</div>;
export const routing_detail_16 = (p:any)=> <div>routing 16 VRP</div>;
export const routing_detail_17 = (p:any)=> <div>routing 17 TSP</div>;
export const routing_detail_18 = (p:any)=> <div>routing 18 Dijkstra</div>;
export const routing_detail_19 = (p:any)=> <div>routing 19 time windows</div>;