import React from 'react';
export const dispatchDetails = () => <div>dispatch distinct</div>;
export const dispatch_detail_0 = (p:any)=> <div>dispatch 0 assignment</div>;
export const dispatch_detail_1 = (p:any)=> <div>dispatch 1 scheduling</div>;
export const dispatch_detail_2 = (p:any)=> <div>dispatch 2 load board</div>;
export const dispatch_detail_3 = (p:any)=> <div>dispatch 3 tender</div>;
export const dispatch_detail_4 = (p:any)=> <div>dispatch 4 assignment</div>;
export const dispatch_detail_5 = (p:any)=> <div>dispatch 5 scheduling</div>;
export const dispatch_detail_6 = (p:any)=> <div>dispatch 6 load board</div>;
export const dispatch_detail_7 = (p:any)=> <div>dispatch 7 tender</div>;
export const dispatch_detail_8 = (p:any)=> <div>dispatch 8 assignment</div>;
export const dispatch_detail_9 = (p:any)=> <div>dispatch 9 scheduling</div>;
export const dispatch_detail_10 = (p:any)=> <div>dispatch 10 load board</div>;
export const dispatch_detail_11 = (p:any)=> <div>dispatch 11 tender</div>;
export const dispatch_detail_12 = (p:any)=> <div>dispatch 12 assignment</div>;
export const dispatch_detail_13 = (p:any)=> <div>dispatch 13 scheduling</div>;
export const dispatch_detail_14 = (p:any)=> <div>dispatch 14 load board</div>;
export const dispatch_detail_15 = (p:any)=> <div>dispatch 15 tender</div>;
export const dispatch_detail_16 = (p:any)=> <div>dispatch 16 assignment</div>;
export const dispatch_detail_17 = (p:any)=> <div>dispatch 17 scheduling</div>;
export const dispatch_detail_18 = (p:any)=> <div>dispatch 18 load board</div>;
export const dispatch_detail_19 = (p:any)=> <div>dispatch 19 tender</div>;